# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""remove_chart_id_from_bulletins

Revision ID: 0cd46b945a82
Revises: eea956e60ca6
Create Date: 2025-05-21 08:52:05.252548

"""

# revision identifiers, used by Alembic.
revision = '0cd46b945a82'
down_revision = 'eea956e60ca6' # Please verify this matches the actual previous migration ID in your versions folder.

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql # Not needed for this focused migration

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the foreign key constraint associated with chart_id on the bulletins table.
    # The constraint name 'bulletins_chart_id_fkey' is typical for PostgreSQL. 
    # If using a different DB or custom naming, this might need adjustment.
    try:
        op.drop_constraint('bulletins_chart_id_fkey', 'bulletins', type_='foreignkey')
    except Exception as e:
        # Log or print warning if constraint doesn't exist, but don't fail the migration
        print(f"Info: Constraint 'bulletins_chart_id_fkey' not found or could not be dropped (may have been removed manually or in a previous migration): {e}")

    # Drop the chart_id column from the bulletins table.
    try:
        op.drop_column('bulletins', 'chart_id')
    except Exception as e:
        # Log or print warning if column doesn't exist
        print(f"Info: Column 'bulletins.chart_id' not found or could not be dropped (may have been removed manually or in a previous migration): {e}")
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add the chart_id column back to the bulletins table.
    # Ensure this matches the original column definition.
    op.add_column('bulletins', sa.Column('chart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Recreate the foreign key constraint.
    # Assumes 'slices' is the referenced table and 'id' is the referenced column.
    op.create_foreign_key(
        'bulletins_chart_id_fkey', 
        'bulletins', 
        'slices', 
        ['chart_id'], 
        ['id']
    )
    # ### end Alembic commands ###