# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""add_channel_to_disseminated_bulletin_logs

Revision ID: d2b63d87b37e
Revises: 0cd46b945a82
Create Date: 2025-05-22 08:49:16.335378

"""

# revision identifiers, used by Alembic.
revision = 'd2b63d87b37e'
down_revision = '0cd46b945a82'

from alembic import op
import sqlalchemy as sa
# It's good practice to keep sqlalchemy.dialects import if specific types were used,
# but for this simplified version, it might not be strictly necessary.
# from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - ###
    # ### We are manually adjusting this migration to ONLY add the 'channel' column ###
    # ### to 'disseminated_bulletin_logs' table.                                   ###
    # ### All other auto-detected changes have been removed.                        ###
    
    op.add_column('disseminated_bulletin_logs', sa.Column('channel', sa.String(length=50), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - ###
    # ### We are manually adjusting this migration to ONLY drop the 'channel' column ###
    # ### from 'disseminated_bulletin_logs' table.                                  ###
    # ### All other auto-detected changes have been removed.                       ###

    op.drop_column('disseminated_bulletin_logs', 'channel')
    
    # ### end Alembic commands ###
