# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Add WhatsAppGroup model and link to DisseminatedBulletinLog

Revision ID: dc9eb348ec83
Revises: 6fb08134f1a6
Create Date: 2025-05-23 02:12:52.374395

"""

# revision identifiers, used by Alembic.
revision = 'dc9eb348ec83'
down_revision = '6fb08134f1a6'

from alembic import op
import sqlalchemy as sa
# It's good practice to keep imports that might be used by SA types, even if minimal.
# from sqlalchemy.dialects import postgresql 

def upgrade():
    # ### commands auto generated by Alembic - THIS SECTION IS NOW ADJUSTED ###
    op.create_table('whatsapp_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_numbers', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], name='fk_whatsapp_groups_changed_by_fk'),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], name='fk_whatsapp_groups_created_by_fk'),
    sa.PrimaryKeyConstraint('id', name='pk_whatsapp_groups'),
    sa.UniqueConstraint('name', name='uq_whatsapp_groups_name')
    )
    op.add_column('disseminated_bulletin_logs', sa.Column('whatsapp_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_disseminated_bulletin_logs_whatsapp_group_id', # Explicit constraint name
        'disseminated_bulletin_logs', 
        'whatsapp_groups', 
        ['whatsapp_group_id'], 
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - THIS SECTION IS NOW ADJUSTED ###
    op.drop_constraint(
        'fk_disseminated_bulletin_logs_whatsapp_group_id', # Explicit constraint name
        'disseminated_bulletin_logs', 
        type_='foreignkey'
    )
    op.drop_column('disseminated_bulletin_logs', 'whatsapp_group_id')
    op.drop_table('whatsapp_groups')
    # ### end Alembic commands ###
