# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""add_m2m_whatsapp_dissemination

Revision ID: 27f27932464b
Revises: 1bc8bcf2216d
Create Date: 2025-05-29 08:07:19.590427

"""

# revision identifiers, used by Alembic.
revision = '27f27932464b'
down_revision = '1bc8bcf2216d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dissemination_whatsapp_group_association',
    sa.Column('disseminated_bulletin_log_id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disseminated_bulletin_log_id'], ['disseminated_bulletin_logs.id'], ),
    sa.ForeignKeyConstraint(['whatsapp_group_id'], ['whatsapp_groups.id'], ),
    sa.PrimaryKeyConstraint('disseminated_bulletin_log_id', 'whatsapp_group_id')
    )
    op.drop_constraint('fk_disseminated_bulletin_logs_whatsapp_group_id', 'disseminated_bulletin_logs', type_='foreignkey')
    op.drop_column('disseminated_bulletin_logs', 'whatsapp_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disseminated_bulletin_logs', sa.Column('whatsapp_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_disseminated_bulletin_logs_whatsapp_group_id', 'disseminated_bulletin_logs', 'whatsapp_groups', ['whatsapp_group_id'], ['id'])
    op.drop_table('dissemination_whatsapp_group_association')
    # ### end Alembic commands ###

