# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""make_email_group_id_nullable_in_logs

Revision ID: 6fb08134f1a6
Revises: d2b63d87b37e
Create Date: 2025-05-22 09:07:00.020530

"""

# revision identifiers, used by Alembic.
revision = '6fb08134f1a6'
down_revision = 'd2b63d87b37e' # Should point to the previous migration

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql # Likely not needed for this simple change

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually adjusted to only alter the email_group_id column to be nullable.
    op.alter_column('disseminated_bulletin_logs', 'email_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually adjusted to revert email_group_id column to be non-nullable.
    op.alter_column('disseminated_bulletin_logs', 'email_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
