# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""bulletin_multiple_image_attachments_new_table

Revision ID: eea956e60ca6
Revises: 0b94561d71bd
Create Date: 2025-05-21 08:04:34.876559

"""

# revision identifiers, used by Alembic.
revision = 'eea956e60ca6'
down_revision = '0b94561d71bd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin_image_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('bulletins', 'image_attachments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletins', sa.Column('image_attachments', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('bulletin_image_attachments')
    # ### end Alembic commands ###
