# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Add position, gender preference, age category, disability, and contact number to user model

Revision ID: 1cb9260fe811
Revises: 27f27932464b
Create Date: 2025-06-27 04:16:25.254774

"""

# revision identifiers, used by Alembic.
revision = '1cb9260fe811'
down_revision = '27f27932464b'

from alembic import op
import sqlalchemy as sa

def column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns to ab_register_user only if they don't exist
    if not column_exists('ab_register_user', 'position'):
        op.add_column('ab_register_user', sa.Column('position', sa.String(length=100), nullable=True))
    if not column_exists('ab_register_user', 'gender_preference'):
        op.add_column('ab_register_user', sa.Column('gender_preference', sa.String(length=50), nullable=True))
    if not column_exists('ab_register_user', 'age_category'):
        op.add_column('ab_register_user', sa.Column('age_category', sa.String(length=50), nullable=True))
    if not column_exists('ab_register_user', 'has_disability'):
        op.add_column('ab_register_user', sa.Column('has_disability', sa.String(length=10), nullable=True))
    if not column_exists('ab_register_user', 'disability_type'):
        op.add_column('ab_register_user', sa.Column('disability_type', sa.String(length=255), nullable=True))
    if not column_exists('ab_register_user', 'contact_number'):
        op.add_column('ab_register_user', sa.Column('contact_number', sa.String(length=50), nullable=True))
    
    # Drop columns from ab_register_user only if they exist
    if column_exists('ab_register_user', 'age_range'):
        op.drop_column('ab_register_user', 'age_range')
    if column_exists('ab_register_user', 'gender'):
        op.drop_column('ab_register_user', 'gender')
    
    # Add columns to ab_user only if they don't exist
    if not column_exists('ab_user', 'position'):
        op.add_column('ab_user', sa.Column('position', sa.String(length=100), nullable=True))
    if not column_exists('ab_user', 'gender_preference'):
        op.add_column('ab_user', sa.Column('gender_preference', sa.String(length=50), nullable=True))
    if not column_exists('ab_user', 'age_category'):
        op.add_column('ab_user', sa.Column('age_category', sa.String(length=50), nullable=True))
    if not column_exists('ab_user', 'has_disability'):
        op.add_column('ab_user', sa.Column('has_disability', sa.String(length=10), nullable=True))
    if not column_exists('ab_user', 'disability_type'):
        op.add_column('ab_user', sa.Column('disability_type', sa.String(length=255), nullable=True))
    if not column_exists('ab_user', 'contact_number'):
        op.add_column('ab_user', sa.Column('contact_number', sa.String(length=50), nullable=True))
    
    # Drop columns from ab_user only if they exist
    if column_exists('ab_user', 'gender'):
        op.drop_column('ab_user', 'gender')
    if column_exists('ab_user', 'age_range'):
        op.drop_column('ab_user', 'age_range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_user', sa.Column('age_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ab_user', sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('ab_user', 'contact_number')
    op.drop_column('ab_user', 'disability_type')
    op.drop_column('ab_user', 'has_disability')
    op.drop_column('ab_user', 'age_category')
    op.drop_column('ab_user', 'gender_preference')
    op.drop_column('ab_user', 'position')
    op.add_column('ab_register_user', sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ab_register_user', sa.Column('age_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('ab_register_user', 'contact_number')
    op.drop_column('ab_register_user', 'disability_type')
    op.drop_column('ab_register_user', 'has_disability')
    op.drop_column('ab_register_user', 'age_category')
    op.drop_column('ab_register_user', 'gender_preference')
    op.drop_column('ab_register_user', 'position')
    # ### end Alembic commands ###
