engines:
  csslint:
    enabled: false
  eslint:
    enabled: true
    config:
      config: caravel/assets/.eslintrc
  pep8:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
  - "caravel/assets/**.js"
  - "caravel/assets/**.jsx"
exclude_paths:
- ".*"
- "**.pyc"
- "**.gz"
- "env/"
- "tests/"
- "caravel/assets/images/"
- "caravel/assets/vendor/"
- "caravel/assets/node_modules/"
- "caravel/assets/javascripts/dist/"
