doc-warnings: yes
test-warnings: no
strictness: medium
max-line-length: 90
uses:
    - flask
autodetect: yes
pylint:
  disable:
    - cyclic-import
  options:
    docstring-min-length: 10
ignore-paths:
    - docs
    - panoramix/migrations/env.py
    - panoramix/ascii_art.py
ignore-patterns:
    - ^example/doc_.*\.py$
    - (^|/)docs(/|$)
python-targets:
    - 2
    - 3
