language: python
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.wheelhouse/
install:
  - pip wheel -w $HOME/.wheelhouse -f $HOME/.wheelhouse -r requirements.txt
  - pip install --find-links=$HOME/.wheelhouse --no-index -rrequirements.txt
  - python setup.py install

# command to run tests
script: bash run_tests.sh
after_success: coveralls
