language: python
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.wheelhouse/
before_install:
  - rm -rf ~/.npm
  - mkdir ~/.npm
install:
  - pip wheel -w $HOME/.wheelhouse -f $HOME/.wheelhouse .
  - pip wheel -w $HOME/.wheelhouse -f $HOME/.wheelhouse -r dev-reqs.txt
  - pip install --find-links=$HOME/.wheelhouse --no-index .
  - cd caravel/assets
  - npm install
  - npm run lint
  - npm run prod
  - cd $TRAVIS_BUILD_DIR
script: bash run_tests.sh
after_success:
  - coveralls
