language: python
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.wheelhouse/
install:
  - pip wheel -w $HOME/.wheelhouse -f $HOME/.wheelhouse -r requirements.txt
  - pip install --find-links=$HOME/.wheelhouse --no-index -rrequirements.txt
  - python setup.py install
  - cd dashed/assets
  - "touch $HOME/.npm/foo.lock; rm -f $HOME/.npm/*.lock"
  - npm install
  - npm run prod
  - cd $TRAVIS_BUILD_DIR
script: bash run_tests.sh
after_success:
  - coveralls
  - cd dashed/assets
  - npm run lint
