version: '3.8'

services:
  weather-forecast:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-forecast
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped 