services:
  disease-predictor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: disease-predictor
    env_file:
      - path: .env # default
        required: true
      - path: .env-local # optional override
        required: false
    volumes:
      - .:/app
      - ../superset-frontend/plugins/preset-chart-deckgl-osm/src/layers/Country/countries/timorleste.geojson:/app/config/timorleste.geojson:ro
    restart: unless-stopped 